
# general
name: "demo_school"
municipality: "demo_muncipality"

# cost specifications
ranker: "FullRanker"
costs: {
  "HeatingCost": {
    "t_weight": 1.0,
    "message_importance": 0.5
  },
  "CapacityCost": {},
  "AmenityCost": {
    "coeff": 0.45
  },
}

# room adjacency matrix
adjacency: [
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 1, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [0, 1, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
    [0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
]

# room descriptions
room_descriptions: [
    {"name": "Room A", "capacity": 30, "amenities": {"whiteboard", "projector"}},
    {"name": "Room B", "capacity": 20, "amenities": {"whiteboard"}},
    {"name": "Room C", "capacity": 10, "amenities": {"projector"}},
    {"name": "Room D", "capacity": 30, "amenities": {"whiteboard", "projector"}},
    {"name": "Room E", "capacity": 15},
    {"name": "Room F", "capacity": 30, "amenities": {"whiteboard"}},
    {"name": "Room G", "capacity": 15, "amenities": {"whiteboard", "screen"}},
    {"name": "Room H", "capacity": 30, "amenities": {"screen"}},
    {"name": "Room I", "capacity": 10, "amenities": {"whiteboard", "projector", "screen"}},
    {"name": "Room J", "capacity": 30},
]
