building: demo_school
municipality: demo_municipality
year: 2022

get_data:
    files:
        - name: bookings
          file_path: assets/demo_bookings.csv
          parse_params:
            drop_empty_rooms: true
            aggregation_method: binary
        - name: energy
          file_path: assets/demo_energy.csv
          parse_params:
            measure_points:
                - 12892834
            measure_types:
                - electricity


preprocessing:
  booking_hours_threshold: 0
  drop_nights_and_school_hours: true
  ventilation:
    is_day: true


train:
  target: electricity
  estimator: RidgeRegression
  cv_folds: 5
  alpha_min: 0.01
  alpha_max: 100
