site_name: Thermo
repo_url: https://github.com/NTTDATAInnovation/thermo

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: docs/overrides

nav:
  - Introduction: index.md
  - Principles behind the code:
      - The heat equation: thermo.md
      - School as a graph: graph.md
      - Model for capacity: capacity.md
  - Reference:
      - Recommender and Recommendation: ref/recommender.md
      - Rankers: ref/ranker.md
      - Costs: ref/cost.md


markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.arithmatex:
      generic: true
  - tables

plugins:
  - search:
  - mkdocstrings: # This is the config for the python docs
      handlers:
        python:
          options:
            docstring_style: google
            separate_signature: yes
            show_signature_annotations: true
            show_source: true
            show_root_full_path: yes
            merge_init_into_class: yes
            show_submodules: true
  - print-site:
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
watch: # this is optional, it helps to test the documentation locally.
  - thermo # or wherever you have your python code.

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
