name: Test

on:
  push:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.21
        shell: bash
      - name: Check workflow files
        run: ./actionlint -color
        shell: bash

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-poetry-env
        with:
          python-version: '3.10'
      - run: poetry run pytest


  test_dvc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Get poetry
        uses: snok/install-poetry@v1
      - name: Get dvc
        run: poetry install --only dev
      - name: Dry run dvc workflows
        run: bash  ./.github/custom_scripts/dvc_dryrun.sh
        shell: bash
